flags: {}

packages:
- '.'

extra-deps:
- aeson-lens-0.5.0.0
- twitter-conduit-0.1.0
- twitter-types-0.7.0
- twitter-types-lens-0.7.0
- wai-dispatch-0.1
- yesod-routes-1.2.0.7
- acid-state-0.12.4
- path-pieces-0.1.5
    
resolver: lts-2.9
